name: Check formatting
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: c-hive/gha-yarn-cache@v1

      - name: Install modules
        run: yarn

      - name: Check formatting
        run: |
          yarn format:check
